# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

trigger:
    - master

jobs:
    - job: 'gradlew_build'

      pool:
          vmImage: 'macOS-10.14'

      steps:
          - template: clone-src-with-deps.yaml

          - task: Gradle@2
            displayName: build and test dev ai-android service
            inputs:
              workingDirectory: '$(system.defaultWorkingDirectory)/AccessibilityInsightsForAndroidService'
              gradleWrapperFile: 'AccessibilityInsightsForAndroidService/gradlew'
              gradleOptions: '-Xmx3072m'
              options: -S
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml'
              tasks: 'build'

          - task: Bash@3
            inputs:
              targetType: 'filePath'
              filePath: $(System.DefaultWorkingDirectory)/pipeline/start-emulator.sh
          
          - task: NodeTool@0
            inputs:
                versionSpec: '12.13.0'
            displayName: use node 12.13.0
            timeoutInMinutes: 2

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: npm install adbkit-apkreader

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: npm install appium-adb

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: node $(System.DefaultWorkingDirectory)/appium.js