# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

trigger:
    - master

jobs:
    - job: 'mac_testing'

      pool:
          vmImage: 'macOS-10.14'

      steps:
          - template: test-appium-script.yaml
