# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

trigger:
    - master

jobs:
    - job: 'mac_testing'

      pool:
          vmImage: 'macOS-10.14'

      steps:
          - template: test-appium-script.yaml

    - job: 'ubuntu_testing'

      pool:
          vmImage: 'ubuntu-16.04'

      steps:
          - template: test-appium-script.yaml

    - job: 'windows_testing'

      pool:
          vmImage: 'windows-2019'

      steps:
          - template: test-appium-script.yaml

